name: Build, Test and Analyze

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FLUTTER_VERSION: '3.10.5'

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: GITHUB_TOKEN
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: FLUTTER_VERSION
          channel: 'stable'
          cache: true
      - name: Generate files
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          dart pub global activate protoc_plugin
          chmod +x generate_protos.sh
          ./generate_protos.sh
        
  analyze:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: FLUTTER_VERSION
          channel: 'stable'
          cache: true
      - name: Static Analysis
        run: flutter analyze

  unit-tests:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: FLUTTER_VERSION
          channel: 'stable'
          cache: true
      - name: Unit Tests
        run: flutter test test/unit

  widget-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: FLUTTER_VERSION
          channel: 'stable'
          cache: true
      - name: Unit Tests
        run: flutter test test/unit
      - name: Widget Tests
        run: flutter test test/widget