name: Build, Test and Analyze

on: [push, pull_request]

jobs:
  setup:
    uses: ./.github/workflows/setup-flutter.yml@main
    with:
      flutter-version: '3.10.5'

  analyze:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Analyze
        run: flutter analyze

      #- name: Unit Tests
      #   run: flutter test test/unit
      # - name: Widget Tests
      #   run: flutter test test/widget
      # - name: Build release package
      #   run: flutter build apk --release
      # - name: Archive build artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: apk
      #     path: |
      #       build/app/outputs/flutter-apk/app-release.apk
            
